# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @useDynLib chocR
NULL

dKernel <- function(grid, obs, probs, rooti) {
    .Call(`_chocR_dKernel`, grid, obs, probs, rooti)
}

get_root_i <- function(chol) {
    .Call(`_chocR_get_root_i`, chol)
}

rKernel <- function(n, x, chol, probs = NULL) {
    .Call(`_chocR_rKernel`, n, x, chol, probs)
}

computeChoc <- function(grid, list_data, list_weights, rooti) {
    .Call(`_chocR_computeChoc`, grid, list_data, list_weights, rooti)
}

computeIvlev <- function(realised, avalaible) {
    .Call(`_chocR_computeIvlev`, realised, avalaible)
}

